version: 2

models:
  - name: details
    tests:
      - dbt_utils.equality:
          compare_model: "{{ ref( target.name | replace('unit-test_','details_expected_') ) }}"
          compare_columns:
            - name
            - id
            - city

sources:
  - name: snowflake
    database: dbt_test
    schema: raw
    tables: 
      - name: customer
      - name: contact

  - name: test_snowflake
    database: dbt_test
    schema: unit_testing
    tables:
      - name: test_contact_1
      - name: test_customer_1
      - name: test_contact_2
      - name: test_customer_2