dbt_insta:
  outputs:
    dev:
      account: "{{ env_var('SNOWSQL_ACCOUNT')}}"
      database: "{{ env_var('SNOWSQL_DATABASE')}}"
      password: "{{ env_var('SNOWSQL_PWD')}}"
      role: "{{ env_var('SNOWSQL_ROLE')}}"
      schema: MAIN
      threads: 5
      type: snowflake
      user: "{{ env_var('SNOWSQL_USER')}}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE')}}"
    unit-test_1:
      account: "{{ env_var('SNOWSQL_ACCOUNT')}}"
      database: "{{ env_var('SNOWSQL_DATABASE')}}"
      password: "{{ env_var('SNOWSQL_PWD')}}"
      role: "{{ env_var('SNOWSQL_ROLE')}}"
      schema: UNIT_TESTING
      threads: 5
      type: snowflake
      user: "{{ env_var('SNOWSQL_USER')}}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE')}}"
    unit-test_2:
      account: "{{ env_var('SNOWSQL_ACCOUNT')}}"
      database: "{{ env_var('SNOWSQL_DATABASE')}}"
      password: "{{ env_var('SNOWSQL_PWD')}}"
      role: "{{ env_var('SNOWSQL_ROLE')}}"
      schema: UNIT_TESTING
      threads: 5
      type: snowflake
      user: "{{ env_var('SNOWSQL_USER')}}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE')}}"
  target: dev