# This is a basic workflow to help you get started with Actions

name: Run DBT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
  SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
  SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
  SNOWSQL_SCHEMA: ${{ github.ref_name }}
  SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.assertions }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install python packages
        run: pip3 install -r requirements.txt
      - name: Check DBT Version
        run : dbt --version
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.23-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.23-linux_x86_64.bash
      - name: List the directory
        run: |
          ls -la && pwd
      - name: Fetch Manifest file
        run: mkdir ../prior_state && ~/bin/snowsql -q "select Manifest from DBT_TEST.UTILL_COMMON.DBT_STATE order by insertion_time desc limit 1" -w  MINE -o friendly=false -o timing=false -o header=false -o output_format=plain > ../prior_state/manifest.json
      - name: Get manifest file
        id: vars
        run: echo ::set-output name=manifest::$(cat ../prior_state/manifest.json)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}
      - name: Read manifest
        run: cat ../prior_state/manifest.json
      - name: Run DBT
        run: dbt run
      - name: Generate Manifest file
        run: dbt compile
      - name: Move the generated file
        run: cat ./target/manifest.json && mv ./target/manifest.json ../prior_state/manifest.json
      - name: Upload manifest
        run: ~/bin/snowsql -q "PUT file://../prior_state/manifest.json @DBT_TEST.UTILL_COMMON.%DBT_STATE" && ~/bin/snowsql -q 'COPY INTO DBT_TEST.UTILL_COMMON.DBT_STATE from (SELECT $1,current_timestamp() from @DBT_TEST.UTILL_COMMON.%DBT_STATE ) file_format = (type = json ) PURGE = TRUE'


      
      
  