# This is a basic workflow to help you get started with Actions

name: verify DBT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
  SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
  SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
  SNOWSQL_SCHEMA: ${{ github.ref_name }}
  SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.assertions }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install python packages
        run: pip3 install -r requirements.txt
      - name: Check DBT Version
        run : dbt --version
      - name: Run dbt deps
        run: dbt deps
      - name: Run dbt seeds
        run: dbt seed --target unit-test_1
      
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.23-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.23-linux_x86_64.bash
      - name: Fetch Manifest file
        run: mkdir ../prior_state && ~/bin/snowsql -q "select Manifest from DBT_TEST.UTILL_COMMON.DBT_STATE order by insertion_time desc limit 1" -w  MINE -o friendly=false -o timing=false -o header=false -o output_format=plain > ../prior_state/manifest.json
      - name : Drop all tables in testing schema
        run : ~/bin/snowsql -q "drop table if exists DBT_TEST.UNIT_TESTING.DETAILS;"
      - name: Run DBT first Pass
        run: dbt run --target unit-test_1 --select state:modified+ --defer --state ../prior_state/
      - name: Run Test first Pass
        run: dbt test --target unit-test_1 --select state:modified+ --defer --state ../prior_state/
      - name: Run DBT second Pass
        run: dbt run --target unit-test_2 --select state:modified+ --defer --state ../prior_state/
      - name: Run Test second Pass
        run: dbt test --target unit-test_2 --select state:modified+ --defer --state ../prior_state/
      
  